'use client';
import { useEffect, useRef, useState } from 'react';
import { flushSync } from 'react-dom';
import { ImagePlus, Printer, ShieldCheck, Upload, Download, RotateCw, Trash2, BookmarkPlus, HelpCircle, Check, FileImage, Files } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Slider } from '@/components/ui/slider';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { DEFAULT, PRESETS, SHEETS, LIMITS, arrange, validateSettings, type Settings, type Preset } from '@/lib/geometry';
import { decode, renderCanvas, encodeJPEG, download, filename, type Asset } from '@/lib/images';

function Choice({label,value,options,onChange,disabled=false}:{label:string;value:string;options:{value:string;label:string}[];onChange:(value:string)=>void;disabled?:boolean}){
  return <div className="field"><span className="field-label">{label}</span><Select value={value} onValueChange={v=>v&&onChange(v)} disabled={disabled}><SelectTrigger aria-label={label} className="w-full h-10"><SelectValue>{options.find(o=>o.value===value)?.label??'Custom settings'}</SelectValue></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></div>;
}
function Numeric({label,value,min,max,onChange,integer=false}:{label:string;value:number;min:number;max:number;onChange:(value:number)=>void;integer?:boolean}){
  const [draft,setDraft]=useState(String(value));
  useEffect(()=>setDraft(String(value)),[value]);
  function commit(){let n=Number(draft);if(!Number.isFinite(n)||draft==='')n=value;n=Math.max(min,Math.min(max,integer?Math.round(n):n));setDraft(String(n));onChange(n);}
  return <label className="field"><span className="field-label">{label}</span><Input type="number" min={min} max={max} step={integer?1:.1} value={draft} onChange={e=>setDraft(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/></label>;
}
function Range({label,value,min,max,step=1,onChange}:{label:string;value:number;min:number;max:number;step?:number;onChange:(v:number)=>void}){
  return <div className="range-field"><div className="field-label">{label}<span>{label==='Zoom'?`${value.toFixed(2)}×`:`${value}%`}</span></div><Slider aria-label={label} value={[value]} min={min} max={max} step={step} onValueChange={v=>onChange(Array.isArray(v)?v[0]:v)}/></div>;
}
function ProcessedImage({asset,className=''}:{asset:Asset;className?:string}){
  const canvas=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{if(!canvas.current)return;const rendered=renderCanvas(asset.image,asset.settings,className?600:96);canvas.current.width=rendered.width;canvas.current.height=rendered.height;canvas.current.getContext('2d')?.drawImage(rendered,0,0);},[asset.image,asset.settings,className]);
  return <canvas ref={canvas} className={className} role="img" aria-label={`Prepared ${asset.name}`}/>;
}
const STORAGE='print-form-desk.presets.v1';
type Registry={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>};

export default function Desk(){
  const input=useRef<HTMLInputElement>(null);
  const [assets,setAssets]=useState<Asset[]>([]),[selected,setSelected]=useState('');
  const [presetId,setPresetId]=useState('photo'),[saved,setSaved]=useState<Preset[]>([]);
  const [sheetId,setSheetId]=useState<keyof typeof SHEETS>('a4'),[tab,setTab]=useState('edit'),[page,setPage]=useState(0);
  const [busy,setBusy]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState('');
  const [dialog,setDialog]=useState<'preset'|'help'|'plans'|null>(null),[presetName,setPresetName]=useState('');
  const state=useRef({assets,selected,busy});state.current={assets,selected,busy};
  const active=assets.find(a=>a.id===selected)??assets[0];
  const presets=[...PRESETS,...saved],sheet=SHEETS[sheetId];
  let layout:ReturnType<typeof arrange>=[],layoutError='';
  try{layout=arrange(assets,sheet);}catch(e){layoutError=(e as Error).message;}
  const pages=(layout.at(-1)?.page??-1)+1,visiblePage=Math.min(page,Math.max(0,pages-1));
  useEffect(()=>{
    try{const data=JSON.parse(localStorage.getItem(STORAGE)??'[]');if(!Array.isArray(data))throw new Error();setSaved(data.slice(0,30).map(p=>{if(typeof p.id!=='string'||!p.id.startsWith('saved-')||typeof p.name!=='string'||p.name.length>60)throw new Error();return {...p,settings:validateSettings(p.settings)};}));}catch{setError('Saved presets could not be loaded. You can still prepare files and save new presets.');}
    return ()=>state.current.assets.forEach(a=>URL.revokeObjectURL(a.url));
  },[]);
  function update(patch:Partial<Settings>){if(!active||busy)return;setAssets(list=>list.map(a=>a.id===active.id?{...a,settings:{...a.settings,...patch}}:a));setMessage('');setError('');}
  function choosePreset(id:string){const preset=presets.find(p=>p.id===id);if(!preset)return;setPresetId(id);if(active)setAssets(list=>list.map(a=>a.id===active.id?{...a,settings:{...preset.settings}}:a));setMessage('');setError('');}
  useEffect(()=>{
    const context=(document as Document & {modelContext?:Registry}).modelContext;if(!context?.registerTool)return;
    const lifecycle=new AbortController();
    const register=(tool:Parameters<Registry['registerTool']>[0])=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{/* Optional browser capability. */}};
    register({name:'read_print_job',description:'Read image count and selected preparation settings. Does not return customer file content or names.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object.');const s=state.current;return {imageCount:s.assets.length,busy:!!s.busy,settings:s.assets.find(a=>a.id===s.selected)?.settings??s.assets[0]?.settings??null};}});
    register({name:'configure_selected_image',description:'Change dimensions, JPEG size limit, crop, copy count or print width of the selected image. Does not export.',inputSchema:{type:'object',properties:Object.fromEntries(Object.entries(LIMITS).map(([key,[minimum,maximum]])=>[key,{type:'number',minimum,maximum}])),minProperties:1,additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const s=state.current;if(s.busy)throw new Error('Wait for the current operation.');const a=s.assets.find(a=>a.id===s.selected)??s.assets[0];if(!a)throw new Error('Choose an image in the workspace first.');if(!input||typeof input!=='object'||Array.isArray(input)||!Object.keys(input).length||Object.keys(input).some(k=>!(k in LIMITS)))throw new Error('Provide only supported settings.');const settings=validateSettings({...a.settings,...input});flushSync(()=>setAssets(list=>list.map(item=>item.id===a.id?{...item,settings}:item)));return {settings};}});
    return ()=>lifecycle.abort();
  },[]);
  async function addFiles(files:File[]){
    if(busy)return;setBusy('Opening images…');setError('');setMessage('');const added:Asset[]=[],errors:string[]=[];
    try{const remaining=30-assets.length;if(files.length>remaining)errors.push(`Only the first ${remaining} files were considered. A job holds up to 30 images.`);
      for(const file of files.slice(0,remaining)){try{const image=await decode(file);added.push({id:crypto.randomUUID(),name:file.name,url:image.src,image,settings:{...(presets.find(p=>p.id===presetId)?.settings??DEFAULT)}});}catch(e){errors.push(`${file.name}: ${(e as Error).message}`);}}
      setAssets(list=>[...list,...added]);if(added.length){setSelected(added[0].id);setMessage(`${added.length} image${added.length===1?'':'s'} added.`);}if(errors.length)setError(errors.join(' '));
    }finally{setBusy('');if(input.current)input.current.value='';}
  }
  function remove(id:string){const asset=assets.find(a=>a.id===id);if(asset)URL.revokeObjectURL(asset.url);const rest=assets.filter(a=>a.id!==id);setAssets(rest);if(selected===id)setSelected(rest[0]?.id??'');setMessage('');setError('');}
  function savePreset(){if(!active||!presetName.trim())return;const next=[...saved,{id:`saved-${crypto.randomUUID()}`,name:presetName.trim().slice(0,60),settings:{...active.settings,zoom:1,x:50,y:50,rotation:0}}];try{if(next.length>30)throw new Error('Delete an old preset first; the limit is 30.');localStorage.setItem(STORAGE,JSON.stringify(next));setSaved(next);setPresetId(next.at(-1)!.id);setDialog(null);setPresetName('');setMessage('Preset saved on this browser. Crop position is reset for each new customer.');}catch(e){setError(`Could not save preset. ${(e as Error).message}`);setDialog(null);}}
  function deletePreset(){try{const next=saved.filter(p=>p.id!==presetId);localStorage.setItem(STORAGE,JSON.stringify(next));setSaved(next);setPresetId('photo');setMessage('Saved preset deleted. Current image settings are unchanged.');}catch{setError('Your browser could not update saved presets.');}}
  async function exportFiles(kind:'jpg'|'zip'|'sheet'|'pdf'){
    if(!active||busy)return;setError('');setMessage('');setBusy('Preparing download…');
    try{
      if(kind==='sheet'&&layoutError)throw new Error(layoutError);
      const chosen=kind==='jpg'?[active]:assets,encoded=new Map<string,Uint8Array>();let total=0;
      for(let i=0;i<chosen.length;i++){setBusy(`Preparing image ${i+1} of ${chosen.length}…`);const blob=await encodeJPEG(chosen[i]);total+=blob.size;encoded.set(chosen[i].id,new Uint8Array(await blob.arrayBuffer()));}
      if(kind==='jpg')download(new Blob([encoded.get(active.id)! as BlobPart],{type:'image/jpeg'}),filename(active.name,assets.indexOf(active)));
      if(kind==='zip'){const {zipSync}=await import('fflate');const entries=Object.fromEntries(assets.map((a,i)=>[filename(a.name,i),encoded.get(a.id)!]));download(new Blob([zipSync(entries,{level:0}) as BlobPart],{type:'application/zip'}),'prepared-images.zip');}
      if(kind==='sheet'||kind==='pdf'){const {printPDF,imagePDF}=await import('@/lib/pdf');const bytes=kind==='sheet'?await printPDF(encoded,layout,sheet):await imagePDF([...encoded.values()]);download(new Blob([bytes as BlobPart],{type:'application/pdf'}),kind==='sheet'?'photo-print-sheet.pdf':'prepared-images.pdf');}
      setMessage(kind==='jpg'?`JPG ready · ${(total/1000).toFixed(1)} KB · ${active.settings.width} × ${active.settings.height} px. Download started.`:kind==='sheet'?`Print sheet ready · ${pages} page${pages===1?'':'s'}. Print at actual size (100%).`:`${chosen.length} prepared images exported. Download started.`);
    }catch(e){setError((e as Error).message||'Could not export this job. Try fewer images.');}finally{setBusy('');}
  }
  const settings=active?.settings;
  return <div className="desk"><header className="topbar"><a href="/" className="brand"><span className="brand-icon"><Printer size={23}/></span><span>Print<span className="brand-light"> & </span>Form<span className="brand-light"> Desk</span></span></a><span className="beta">BETA</span><span className="privacy"><ShieldCheck size={16}/> Files stay on this device</span><Button variant="ghost" onClick={()=>setDialog('help')} aria-label="How to use Print & Form Desk"><HelpCircle size={20}/></Button></header>
    <main className="main"><div className="page-heading"><div><p className="eyebrow">YOUR COUNTER, SIMPLIFIED</p><h1>One job. Ready to go.</h1><p>Prepare photos, signatures and print sheets in one place.</p></div><Button variant="outline" onClick={()=>setDialog('plans')}>Free beta <span className="beta-dot"/></Button></div>
    <div className="status-area" aria-live="polite">{busy&&<p className="status"><span className="spinner"/>{busy}</p>}{message&&!busy&&<p className="status success"><Check size={17}/>{message}</p>}</div>{error&&<div className="error" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}>×</button></div>}
    <div className="workspace"><aside className="panel files-panel"><div className="panel-heading"><h2>Customer files</h2><span>{assets.length}/30</span></div><Button className="upload-button" disabled={!!busy||assets.length>=30} onClick={()=>input.current?.click()}><Upload size={16}/> Add images</Button><input ref={input} hidden multiple type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>void addFiles(Array.from(e.target.files??[]))}/><p className="muted small">JPG, PNG or WebP · up to 20 MB each</p>
      {assets.length?<div className="file-list">{assets.map(a=><div key={a.id} className={`file-row ${active?.id===a.id?'selected':''}`}><button className="file-select" disabled={!!busy} onClick={()=>{setSelected(a.id);setError('');setMessage('');}}><img src={a.url} alt=""/><span><strong>{a.name}</strong><small>{a.settings.width} × {a.settings.height} px · {a.settings.copies} copies</small></span></button><Button variant="ghost" size="icon-sm" disabled={!!busy} aria-label={`Remove ${a.name}`} onClick={()=>remove(a.id)}><Trash2 size={14}/></Button></div>)}</div>:<div className="file-empty"><ImagePlus size={28}/><p>Your customer’s files<br/>will appear here.</p></div>}
      <div className="local-note"><ShieldCheck size={17}/><p>Customer images stay in this tab. Refreshing or closing it clears the job.</p></div>
    </aside>
    <section className="preview-panel"><Tabs value={tab} onValueChange={v=>setTab(String(v))}><div className="preview-toolbar"><TabsList aria-label="Workspace view"><TabsTrigger value="edit"><FileImage size={16}/> Image</TabsTrigger><TabsTrigger value="sheet"><Printer size={16}/> Print sheet</TabsTrigger></TabsList><span>{active?`${assets.length} image${assets.length===1?'':'s'}`:'No files yet'}</span></div>
      <TabsContent value="edit"><div className="preview-stage">{active?<div className="image-artboard"><ProcessedImage asset={active} className="prepared-preview"/><span className="dimension-tag">{active.settings.width} × {active.settings.height} px</span></div>:<div className="empty-preview"><span className="empty-icon"><ImagePlus size={32}/></span><h3>Start with a customer’s photo</h3><p>Choose an image, then adjust the crop and dimensions for the form you’re filling.</p><Button disabled={!!busy} onClick={()=>input.current?.click()}>Choose images <Upload size={16}/></Button></div>}</div>
      {settings&&<fieldset className="crop-controls" disabled={!!busy}><div className="crop-heading"><h2>Adjust the crop</h2><div><Button variant="ghost" onClick={()=>update({rotation:(settings.rotation+90)%360})}><RotateCw size={15}/> Rotate</Button><Button variant="ghost" onClick={()=>update({zoom:1,x:50,y:50,rotation:0})}>Reset</Button></div></div><Range label="Zoom" value={settings.zoom} min={1} max={4} step={.01} onChange={zoom=>update({zoom})}/><div className="two-columns"><Range label="Horizontal" value={settings.x} min={0} max={100} onChange={x=>update({x})}/><Range label="Vertical" value={settings.y} min={0} max={100} onChange={y=>update({y})}/></div><p className="muted small">The preview shows the exported crop. Transparent areas become white.</p></fieldset>}</TabsContent>
      <TabsContent value="sheet"><div className="sheet-options"><Choice label="Paper size" value={sheetId} options={Object.entries(SHEETS).map(([value,s])=>({value,label:s.name}))} onChange={v=>{setSheetId(v as keyof typeof SHEETS);setPage(0);}} disabled={!!busy}/><p className="muted small">5 mm margins · 2 mm gaps<br/>Mixed images follow the file list.</p></div><div className="preview-stage sheet-stage">{layoutError?<p className="sheet-error">{layoutError}</p>:layout.length?<div className="paper" style={{aspectRatio:`${sheet.width}/${sheet.height}`}}>{layout.filter(p=>p.page===visiblePage).map((p,i)=><div key={`${p.id}-${i}`} className="paper-photo" style={{left:`${p.x/sheet.width*100}%`,top:`${p.y/sheet.height*100}%`,width:`${p.width/sheet.width*100}%`,height:`${p.height/sheet.height*100}%`}}><ProcessedImage asset={assets.find(a=>a.id===p.id)!}/></div>)}</div>:<div className="empty-preview"><span className="empty-icon"><Printer size={32}/></span><h3>Your print sheet starts here</h3><p>Add images to lay out copies automatically.</p></div>}</div>{pages>0&&<div className="page-nav"><Button variant="outline" disabled={visiblePage===0} onClick={()=>setPage(visiblePage-1)}>Previous</Button><span>Page {visiblePage+1} of {pages}</span><Button variant="outline" disabled={visiblePage>=pages-1} onClick={()=>setPage(visiblePage+1)}>Next</Button></div>}<div className="preview-footer">Print the PDF at actual size / 100%, with “Fit to page” off.</div></TabsContent>
    </Tabs></section>
    <aside className="panel settings-panel"><div className="panel-heading"><h2>Prepare & export</h2><span>SETTINGS</span></div><fieldset disabled={!!busy}>
      <Choice label={active?'Apply a preset':'Preset for new images'} value={presetId} options={presets.map(p=>({value:p.id,label:p.name}))} onChange={choosePreset} disabled={!!busy}/>
      {!active?<div className="info-note">Add an image to edit dimensions and export. Presets are starting points; check the receiving portal’s current requirements.</div>:settings&&<><div className="two-columns"><Numeric label="Width (px)" value={settings.width} min={32} max={2400} integer onChange={width=>update({width})}/><Numeric label="Height (px)" value={settings.height} min={32} max={2400} integer onChange={height=>update({height})}/></div><Numeric label="Maximum JPG size (KB)" value={settings.maxKB} min={5} max={5000} onChange={maxKB=>update({maxKB})}/><p className="muted small size-help">1 KB = 1,000 bytes. We reduce JPEG quality while keeping your pixel dimensions.</p>{(settings.width>active.image.naturalWidth||settings.height>active.image.naturalHeight)&&<p className="warning">This enlarges the source image and may look soft.</p>}
      <div className="two-columns"><Numeric label="Print width (mm)" value={settings.printWidth} min={5} max={190} onChange={printWidth=>update({printWidth})}/><Numeric label="Sheet copies" value={settings.copies} min={1} max={40} integer onChange={copies=>update({copies})}/></div><p className="muted small size-help">Print height: {(settings.printWidth*settings.height/settings.width).toFixed(1)} mm · proportions preserved</p><div className="preset-actions"><Button variant="outline" onClick={()=>setDialog('preset')}><BookmarkPlus size={15}/> Save preset</Button>{presetId.startsWith('saved-')&&<Button variant="ghost" aria-label="Delete selected saved preset" onClick={deletePreset}><Trash2 size={15}/></Button>}</div>
      <Button variant="ghost" className="apply-all" disabled={assets.length<2} onClick={()=>{setAssets(list=>list.map(a=>({...a,settings:{...settings,zoom:a.settings.zoom,x:a.settings.x,y:a.settings.y,rotation:a.settings.rotation}})));setMessage('Dimensions, size limit and print settings applied to all images. Individual crop positions kept.');}}>Apply size settings to all {assets.length} images</Button><div className="export-section"><Button className="export-primary" onClick={()=>void exportFiles('jpg')}><Download size={17}/> Download this JPG</Button><div className="two-columns"><Button variant="outline" onClick={()=>void exportFiles('zip')}><Files size={15}/> All as ZIP</Button><Button variant="outline" disabled={!!layoutError} onClick={()=>void exportFiles('sheet')}><Printer size={15}/> Print PDF</Button></div><Button variant="ghost" className="full-width" onClick={()=>void exportFiles('pdf')}>Images to PDF · one per A4 page</Button><p className="muted small">PDFs use the prepared crops. Copy counts apply only to the print sheet.</p></div></>}
    </fieldset></aside></div><footer className="desk-footer"><span><ShieldCheck size={15}/> No image uploads. No account needed for this beta.</span><button onClick={()=>setDialog('help')}>How it works</button></footer></main>
    <Dialog open={dialog!==null} onOpenChange={open=>{if(!open)setDialog(null);}}><DialogContent className="desk-dialog sm:max-w-lg"><DialogHeader><DialogTitle>{dialog==='preset'?'Save a reusable preset':dialog==='plans'?'Free while we build with shops':'A job, from image to download'}</DialogTitle><DialogDescription>{dialog==='preset'?'Keep dimensions and print settings on this browser. Customer files and crop positions are never saved.':dialog==='plans'?'Every tool in this beta is currently unlocked.':'Prepare each file, then download individual images or a complete print sheet.'}</DialogDescription></DialogHeader>
      {dialog==='preset'&&<form onSubmit={e=>{e.preventDefault();savePreset();}}><label className="field"><span className="field-label">Preset name</span><Input autoFocus maxLength={60} placeholder="e.g. My shop · small signature" value={presetName} onChange={e=>setPresetName(e.target.value)}/></label><Button type="submit" className="full-width" disabled={!presetName.trim()}>Save on this browser</Button></form>}
      {dialog==='plans'&&<div className="dialog-copy"><p>Use the beta to prepare real jobs. There are no subscriptions or payments enabled yet.</p><p>A future shop plan may add account-based preset syncing and team access. Pricing will be decided after shop feedback; nothing is charged automatically.</p></div>}
      {dialog==='help'&&<div className="dialog-copy"><ol><li><strong>Add images.</strong> Choose photos or signatures. Use a close, well-lit scan for signatures.</li><li><strong>Set the requirements.</strong> Select a starting preset or enter the dimensions and file-size limit from your form.</li><li><strong>Check the crop.</strong> Zoom, reposition or rotate. The tool does not remove backgrounds or verify official photo compliance.</li><li><strong>Download.</strong> JPG exports the selected file, ZIP exports every prepared file once. Print PDF packs the copy counts onto sheets.</li></ol><p>Images to PDF uses your prepared crops, with one image per A4 page. For exact photo sizes, use Print PDF and choose actual size / 100% in the printer dialog.</p><p><strong>Privacy:</strong> images are processed in this browser tab. Saved presets contain settings only. Clear the job by removing files or refreshing the page. Downloads remain in your Downloads folder.</p></div>}
    </DialogContent></Dialog>
  </div>;
}
